name: Security Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SonarQube Scanner
      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v1.1
        with:
          entryPoint: sonar-scanner

      # Step 3: Set SONAR_TOKEN environment variable
      - name: Set SONAR_TOKEN
        run: echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" >> $GITHUB_ENV

      # Step 4: Run SonarQube Scan
      - name: Run SonarQube Scan
        run: sonar-scanner
